version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      DATABASE_URL: postgresql+psycopg://mahmudul:152155809@db:5432/fast_api_starter
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    environment:
      - REDIS_PASSWORD=foobared
    command: ["redis-server", "--requirepass", "foobared"]

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"

volumes:
  postgres_data:
