"""create user model

Revision ID: c60c8c39a550
Revises:
Create Date: 2024-11-01 21:59:44.352545

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c60c8c39a550"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("phone", sa.String(length=14), nullable=False),
        sa.Column("gender", sa.String(length=10), nullable=False),
        sa.Column("dob", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=15), nullable=False),
        sa.Column("is_staff", sa.Boolean(), nullable=True),
        sa.Column("is_superuser", sa.Boolean(), nullable=True),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("last_logged_in_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("password", sa.String(length=150), nullable=False),
        sa.Column(
            "group",
            sa.Enum("BASIC", "STAFF", "MANAGER", "SUPER_ADMIN", name="usergroup"),
            nullable=True,
        ),
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("phone"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
